Update flatbuffers, fixing build on Clang trunk
flatbuffers hard-code general -Werror, which led to builds failing on
clang 11.0.0-++20200307120047+01c48d7d11e-1~exp1~20200307110643.632
with a plethora of
 ../extlib/flatbuffers/include/flatbuffers/flatbuffers.h:1720:25:
 error: definition of implicit copy constructor for
 'TableKeyComparator<reflection::Object>' is deprecated because it has
  a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]